openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-2-0yc5.onrender.com
paths:
  /contacts:
    get:
      security:
        - bearerAuth: []
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      security:
        - bearerAuth: []
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      security:
        - bearerAuth: []
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      security:
        - bearerAuth: []
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      security:
        - bearerAuth: []
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
    
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

      